---
version: 2
updates:
  - package-ecosystem: "gomod"
    # ODF only: disable PR creation, synced from upstream
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "vendor"
    labels:
      - vendor
    groups:
      golang-dependencies:
        patterns:
          - "github.com/golang*"
          - "google.golang.org/*"
          - "golang.org/x/*"
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
      github-dependencies:
        patterns:
          - "github.com*"
        exclude-patterns:
          - "github.com/golang*"
          - "github.com/container-storage-interface/spec"
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "vendor"
    labels:
      - vendor
    groups:
      golang-dependencies:
        patterns:
          - "github.com/golang*"
          - "google.golang.org/*"
          - "golang.org/x/*"
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
      github-dependencies:
        patterns:
          - "github.com*"
        exclude-patterns:
          - "github.com/golang*"
  - package-ecosystem: "github-actions"
    # ODF only: disable PR creation, synced from upstream
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    commit-message:
      prefix: "ci"
    labels:
      - testing
