---
defaults:
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      update_method: rebase
queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - label=api

pull_request_rules:
  - name: remove outdated approvals
    conditions:
      - base~=^(main)|(release-.+)$
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: false
  - name: merge after two approvals (no API changes)
    conditions:
      - base~=^(main)|(release-.+)$
      - label!=api
    actions:
      queue:
        name: default
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: API changes needs approval from a contributor and a reviewer
    conditions:
      - base~=^(main)|(release-.+)$
      - label=api
    actions:
      queue:
        name: default
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: label API change
    conditions:
      - files~=^(api/)
    actions:
      label:
        add:
          - api
  - name: label vendor change
    conditions:
      - files~=^(vendor/)
    actions:
      label:
        add:
          - vendor
