apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-rbdplugin-provisioner
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: Deployment
    name: rook-ceph-operator
    uid: c9971e30-bc23-4c66-aca4-40ad79506164
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-rbdplugin-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-rbdplugin-provisioner
        contains: csi-rbdplugin-metrics
    spec:
      affinity:
        nodeAffinity: {}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-rbdplugin-provisioner
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        - --timeout=150s
        - --retry-interval-start=500ms
        - --leader-election=true
        - --leader-election-namespace=rook-ceph
        - --default-fstype=ext4
        - --extra-create-metadata=true
        env:
        - name: ADDRESS
          value: unix:///csi/csi-provisioner.sock
        image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
        imagePullPolicy: IfNotPresent
        name: csi-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        - --timeout=150s
        - --leader-election
        - --leader-election-namespace=rook-ceph
        - --handle-volume-inuse-error=false
        env:
        - name: ADDRESS
          value: unix:///csi/csi-provisioner.sock
        image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
        imagePullPolicy: IfNotPresent
        name: csi-resizer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --v=5
        - --timeout=150s
        - --csi-address=$(ADDRESS)
        - --leader-election=true
        - --leader-election-namespace=rook-ceph
        env:
        - name: ADDRESS
          value: /csi/csi-provisioner.sock
        image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
        imagePullPolicy: IfNotPresent
        name: csi-attacher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        - --timeout=150s
        - --leader-election=true
        - --leader-election-namespace=rook-ceph
        env:
        - name: ADDRESS
          value: unix:///csi/csi-provisioner.sock
        image: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
        imagePullPolicy: IfNotPresent
        name: csi-snapshotter
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --type=controller
        - --drivernamespace=$(DRIVER_NAMESPACE)
        - --v=5
        - --drivername=rook-ceph.rbd.csi.ceph.com
        env:
        - name: DRIVER_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/cephcsi/cephcsi:canary
        imagePullPolicy: IfNotPresent
        name: csi-omap-generator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
      - args:
        - --metrics-bind-address=0
        - --leader-election-namespace=rook-ceph
        - --driver-name=rook-ceph.rbd.csi.ceph.com
        - --csi-address=$(ADDRESS)
        - --rpc-timeout=150s
        - --health-probe-bind-address=:9998
        - --leader-elect=true
        env:
        - name: ADDRESS
          value: unix:///csi/csi-provisioner.sock
        image: quay.io/csiaddons/volumereplication-operator:v0.1.0
        imagePullPolicy: IfNotPresent
        name: volume-replication
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --node-id=$(NODE_ID)
        - --controller-endpoint=$(PORT)
        - --csi-addons-address=$(CSI_ADDONS_ENDPOINT)
        image: ghcr.io/rakshith-r/sidecar:latest
        imagePullPolicy: "IfNotPresent"
        securityContext:
          privileged: true
        ports:
          - containerPort: 6201
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PORT
          value: ":6201"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_ADDONS_ENDPOINT
          value: unix:///csi/csi-addons.sock
        name: csi-addons-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --nodeid=$(NODE_ID)
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --type=rbd
        - --controllerserver=true
        - --drivername=rook-ceph.rbd.csi.ceph.com
        - --pidlimit=-1
        - --metricsport=9090
        - --metricspath=/metrics
        - --enablegrpcmetrics=false
        - "--csi-addons-endpoint=$(CSI_ADDONS_ENDPOINT)"
        env:
        - name: CSI_ADDONS_ENDPOINT
          value: unix:///csi/csi-addons.sock
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CSI_ENDPOINT
          value: unix:///csi/csi-provisioner.sock
        image: quay.io/cephcsi/cephcsi:canary
        imagePullPolicy: IfNotPresent
        name: csi-rbdplugin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /dev
          name: host-dev
        - mountPath: /sys
          name: host-sys
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
      - args:
        - --type=liveness
        - --endpoint=$(CSI_ENDPOINT)
        - --metricsport=9080
        - --metricspath=/metrics
        - --polltime=60s
        - --timeout=3s
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi-provisioner.sock
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/cephcsi/cephcsi:canary
        imagePullPolicy: IfNotPresent
        name: liveness-prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-csi-rbd-provisioner-sa
      serviceAccountName: rook-csi-rbd-provisioner-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - emptyDir:
          medium: Memory
        name: socket-dir
      - configMap:
          defaultMode: 420
          items:
          - key: csi-cluster-config-json
            path: config.json
          name: rook-ceph-csi-config
        name: ceph-csi-config
      - emptyDir:
          medium: Memory
        name: keys-tmp-dir
      port:

