# permissions for end users to view reclaimspacecronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reclaimspacecronjob-viewer-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - reclaimspacecronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - reclaimspacecronjobs/status
  verbs:
  - get
