# permissions for end users to edit reclaimspacecronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reclaimspacecronjob-editor-role
rules:
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - reclaimspacecronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csiaddons.openshift.io
  resources:
  - reclaimspacecronjobs/status
  verbs:
  - get
