# permissions for end users to view volumegroupreplicationclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volumegroupreplicationclass-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-csi-addons
    app.kubernetes.io/part-of: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
  name: volumegroupreplicationclass-viewer-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplicationclasses/status
  verbs:
  - get
