# permissions for end users to view volumegroupreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volumegroupreplication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-csi-addons
    app.kubernetes.io/part-of: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
  name: volumegroupreplication-viewer-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications/status
  verbs:
  - get
