# permissions for end users to edit volumegroupreplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: volumegroupreplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-csi-addons
    app.kubernetes.io/part-of: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
  name: volumegroupreplication-editor-role
rules:
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.openshift.io
  resources:
  - volumegroupreplications/status
  verbs:
  - get
