// +build !ignore_autogenerated

/*
Copyright 2021 The Kubernetes-CSI-Addons Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceCronJob) DeepCopyInto(out *ReclaimSpaceCronJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceCronJob.
func (in *ReclaimSpaceCronJob) DeepCopy() *ReclaimSpaceCronJob {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceCronJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimSpaceCronJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceCronJobList) DeepCopyInto(out *ReclaimSpaceCronJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReclaimSpaceCronJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceCronJobList.
func (in *ReclaimSpaceCronJobList) DeepCopy() *ReclaimSpaceCronJobList {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceCronJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimSpaceCronJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceCronJobSpec) DeepCopyInto(out *ReclaimSpaceCronJobSpec) {
	*out = *in
	out.JobSpec = in.JobSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceCronJobSpec.
func (in *ReclaimSpaceCronJobSpec) DeepCopy() *ReclaimSpaceCronJobSpec {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceCronJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceCronJobStatus) DeepCopyInto(out *ReclaimSpaceCronJobStatus) {
	*out = *in
	in.CurrentJobStatus.DeepCopyInto(&out.CurrentJobStatus)
	if in.JobHistory != nil {
		in, out := &in.JobHistory, &out.JobHistory
		*out = make([]*ReclaimSpaceJobStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ReclaimSpaceJobStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LastStartTime != nil {
		in, out := &in.LastStartTime, &out.LastStartTime
		*out = (*in).DeepCopy()
	}
	if in.LastCompletionTime != nil {
		in, out := &in.LastCompletionTime, &out.LastCompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceCronJobStatus.
func (in *ReclaimSpaceCronJobStatus) DeepCopy() *ReclaimSpaceCronJobStatus {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceCronJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceJob) DeepCopyInto(out *ReclaimSpaceJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceJob.
func (in *ReclaimSpaceJob) DeepCopy() *ReclaimSpaceJob {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimSpaceJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceJobList) DeepCopyInto(out *ReclaimSpaceJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReclaimSpaceJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceJobList.
func (in *ReclaimSpaceJobList) DeepCopy() *ReclaimSpaceJobList {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReclaimSpaceJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceJobSpec) DeepCopyInto(out *ReclaimSpaceJobSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceJobSpec.
func (in *ReclaimSpaceJobSpec) DeepCopy() *ReclaimSpaceJobSpec {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimSpaceJobStatus) DeepCopyInto(out *ReclaimSpaceJobStatus) {
	*out = *in
	out.ReclaimedSpace = in.ReclaimedSpace.DeepCopy()
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimSpaceJobStatus.
func (in *ReclaimSpaceJobStatus) DeepCopy() *ReclaimSpaceJobStatus {
	if in == nil {
		return nil
	}
	out := new(ReclaimSpaceJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}
